app = "anr-tool-v1"

[build]
  dockerfile = "backend/Dockerfile"
  context = "."  # Use repo root as build context

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
